// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVXn6UPOIlM_w2e2tpatgaCoGgjjY0B8',
    appId: '1:195326385268:web:177aeebf75fba9389a0521',
    messagingSenderId: '195326385268',
    projectId: 'trade-journal-e4eb6',
    authDomain: 'trade-journal-e4eb6.firebaseapp.com',
    storageBucket: 'trade-journal-e4eb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQn52Yv_QsXMrLm-fK7KspXD0ZKAdxO5w',
    appId: '1:195326385268:android:deb0355e937ce2c69a0521',
    messagingSenderId: '195326385268',
    projectId: 'trade-journal-e4eb6',
    storageBucket: 'trade-journal-e4eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3NYn9uxDlki0YkgwPohYDp9se2O7zqKc',
    appId: '1:195326385268:ios:c2c7a72f4e2caee49a0521',
    messagingSenderId: '195326385268',
    projectId: 'trade-journal-e4eb6',
    storageBucket: 'trade-journal-e4eb6.firebasestorage.app',
    iosBundleId: 'com.example.tradeJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3NYn9uxDlki0YkgwPohYDp9se2O7zqKc',
    appId: '1:195326385268:ios:c2c7a72f4e2caee49a0521',
    messagingSenderId: '195326385268',
    projectId: 'trade-journal-e4eb6',
    storageBucket: 'trade-journal-e4eb6.firebasestorage.app',
    iosBundleId: 'com.example.tradeJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnVXn6UPOIlM_w2e2tpatgaCoGgjjY0B8',
    appId: '1:195326385268:web:c8c9a6db2e12f1719a0521',
    messagingSenderId: '195326385268',
    projectId: 'trade-journal-e4eb6',
    authDomain: 'trade-journal-e4eb6.firebaseapp.com',
    storageBucket: 'trade-journal-e4eb6.firebasestorage.app',
  );
}
